/**
 * Universal LLM API service
 * Provides a simple, easy-to-use LLM invocation interface suitable for various use cases
 */

import { StorageService } from '../../core/storage';
import { sendApiRequest, generateGeminiContent } from '../utils/requestUtils';
import { mergeCustomParams } from '../utils/apiUtils';
import {
  ApiConfigItem,
  ApiConfig,
  ApiProtocolFamily,
} from '../../shared/types/api';
import { getApiTimeout } from '../../../utils';
import {
  getProtocolFamilyLabel,
  isGeminiFamily,
} from '../../shared/ApiConfigHelpers';

/**
 * Universal API request options
 */
export interface UniversalApiOptions {
  /** System prompt */
  systemPrompt?: string;
  /** Model temperature (0-2, default 0.7) */
  temperature?: number;
  /** Maximum output tokens */
  maxTokens?: number;
  /** ID of the API configuration to use */
  configId?: string;
  /** Force a specific protocol family */
  forceProvider?: ApiProtocolFamily;
  /** Request timeout in milliseconds (default 30 s; 0 = unlimited) */
  timeout?: number;
  /** Custom request parameters as a JSON string */
  customParams?: string;
  /** Whether to return the raw response */
  rawResponse?: boolean;
}

/**
 * Universal API response result
 */
export interface UniversalApiResult {
  /** Whether it succeeded */
  success: boolean;
  /** The original prompt entered by the user */
  prompt: string;
  /** Response content generated by the AI */
  content: string;
  /** Name of the model used */
  model?: string;
  /** Name of the provider used */
  provider?: string;
  /** Token usage */
  usage?: {
    promptTokens?: number;
    completionTokens?: number;
    totalTokens?: number;
  };
  /** Raw API response (when rawResponse=true) */
  rawData?: any;
  /** Error message (on failure) */
  error?: string;
}

/**
 * Universal LLM API service class
 */
export class UniversalApiService {
  private static instance: UniversalApiService | null = null;
  private storageService: StorageService;

  private constructor() {
    this.storageService = StorageService.getInstance();
  }

  /**
   * Get the singleton instance
   */
  static getInstance(): UniversalApiService {
    if (!UniversalApiService.instance) {
      UniversalApiService.instance = new UniversalApiService();
    }
    return UniversalApiService.instance;
  }

  /**
   * Generic LLM invocation method
   * @param prompt The prompt entered by the user
   * @param options Optional configuration
   * @returns API response result
   */
  async call(
    prompt: string,
    options: UniversalApiOptions = {},
  ): Promise<UniversalApiResult> {
    try {
      // Validate input
      if (!prompt?.trim()) {
        return {
          success: false,
          prompt: prompt || '',
          content: '',
          error: 'Prompt must not be empty',
        };
      }

      // Get the API configuration
      const apiConfig = await this.getApiConfig(
        options.configId,
        options.forceProvider,
      );
      if (!apiConfig) {
        return {
          success: false,
          prompt,
          content: '',
          error: 'No usable API configuration found',
        };
      }

      if (isGeminiFamily(apiConfig.protocolFamily)) {
        return await this.callGoogleGemini(prompt, apiConfig, options);
      } else {
        return await this.callHttpApi(prompt, apiConfig, options);
      }
    } catch (error: any) {
      console.error('UniversalApiService call failed:', error);
      return {
        success: false,
        prompt,
        content: '',
        error: error.message || 'An unknown error occurred during the call',
      };
    }
  }

  /**
   * Call Google Gemini (REST, through the background proxy)
   */
  private async callGoogleGemini(
    prompt: string,
    apiConfig: ApiConfigItem,
    options: UniversalApiOptions,
  ): Promise<UniversalApiResult> {
    try {
      const config = apiConfig.config;

      // Base generation configuration
      const baseGenerationConfig: any = {
        temperature: options.temperature ?? config.temperature ?? 0.7,
      };

      if (options.maxTokens) {
        baseGenerationConfig.maxOutputTokens = options.maxTokens;
      }

      // Merge extra parameters from customParams
      const generationConfig = mergeCustomParams(
        baseGenerationConfig,
        options.customParams || config.customParams,
      );

      const timeout = getApiTimeout(options.timeout);

      // Build the full prompt
      let fullPrompt = prompt;
      if (options.systemPrompt) {
        fullPrompt = `${options.systemPrompt}\n\n${prompt}`;
      }

      console.log('Google Gemini call:', {
        model: config.model,
        prompt: fullPrompt,
        config: generationConfig,
      });

      const result = await generateGeminiContent(config, fullPrompt, {
        generationConfig,
        timeout,
      });
      const response = result.response;
      const content = response.text();

      console.log('Google Gemini response:', content);

      // Build the return result
      const apiResult: UniversalApiResult = {
        success: true,
        prompt,
        content,
        model: config.model,
        provider: getProtocolFamilyLabel(apiConfig.protocolFamily),
      };

      // Add token usage info (if available)
      if (response.usageMetadata) {
        apiResult.usage = {
          promptTokens: response.usageMetadata.promptTokenCount,
          completionTokens: response.usageMetadata.candidatesTokenCount,
          totalTokens: response.usageMetadata.totalTokenCount,
        };
      }

      // If the raw response is requested
      if (options.rawResponse) {
        apiResult.rawData = {
          candidates: response.candidates,
          usageMetadata: response.usageMetadata,
        };
      }

      return apiResult;
    } catch (error: any) {
      console.error('Google Gemini call failed:', error);
      return {
        success: false,
        prompt,
        content: '',
        error: error.message || 'Google Gemini call failed',
      };
    }
  }

  /**
   * Call the HTTP API (OpenAI-compatible format)
   */
  private async callHttpApi(
    prompt: string,
    apiConfig: ApiConfigItem,
    options: UniversalApiOptions,
  ): Promise<UniversalApiResult> {
    try {
      // Build the request parameters
      const requestBody = this.buildRequestBody(
        prompt,
        apiConfig.config,
        options,
      );

      console.log('HTTP API call:', {
        protocolFamily: apiConfig.protocolFamily,
        endpoint: apiConfig.config.apiEndpoint,
        body: requestBody,
      });

      // Send the API request
      const response = await this.sendRequest(
        requestBody,
        apiConfig.config,
        options.timeout,
      );

      if (!response.ok) {
        throw new Error(
          `API request failed: ${response.status} ${response.statusText}`,
        );
      }

      const data = await response.json();

      console.log('HTTP API response:', data);

      // Parse the response
      return this.parseResponse(data, prompt, apiConfig, options.rawResponse);
    } catch (error: any) {
      console.error('HTTP API call failed:', error);
      return {
        success: false,
        prompt,
        content: '',
        error: error.message || 'HTTP API call failed',
      };
    }
  }

  /**
   * Quick call method (uses the default configuration)
   * @param prompt Prompt
   * @param systemPrompt System prompt (optional)
   * @returns API response result
   */
  async quickCall(
    prompt: string,
    systemPrompt?: string,
  ): Promise<UniversalApiResult> {
    return this.call(prompt, {
      systemPrompt,
      temperature: 0.7,
      maxTokens: 1000,
    });
  }

  /**
   * Chat conversation method
   * @param messages Message history
   * @param options Optional configuration
   * @returns API response result
   */
  async chat(
    messages: Array<{ role: 'user' | 'assistant' | 'system'; content: string }>,
    options: UniversalApiOptions = {},
  ): Promise<UniversalApiResult> {
    try {
      const apiConfig = await this.getApiConfig(
        options.configId,
        options.forceProvider,
      );
      if (!apiConfig) {
        return {
          success: false,
          prompt: messages.map((m) => m.content).join('\n'),
          content: '',
          error: 'No usable API configuration found',
        };
      }

      // Build the chat request
      let requestBody: any = {
        model: apiConfig.config.model,
        messages: messages,
        temperature: options.temperature ?? apiConfig.config.temperature ?? 0.7,
      };

      if (options.maxTokens) {
        requestBody.max_tokens = options.maxTokens;
      }

      // Merge custom parameters
      if (options.customParams) {
        requestBody = mergeCustomParams(requestBody, options.customParams);
      } else if (apiConfig.config.customParams) {
        requestBody = mergeCustomParams(
          requestBody,
          apiConfig.config.customParams,
        );
      }

      const response = await this.sendRequest(
        requestBody,
        apiConfig.config,
        options.timeout,
      );

      if (!response.ok) {
        throw new Error(
          `API request failed: ${response.status} ${response.statusText}`,
        );
      }

      const data = await response.json();

      return this.parseResponse(
        data,
        messages[messages.length - 1].content,
        apiConfig,
        options.rawResponse,
      );
    } catch (error: any) {
      return {
        success: false,
        prompt: messages.map((m) => m.content).join('\n'),
        content: '',
        error: error.message || 'Chat call failed',
      };
    }
  }

  /**
   * Check whether the API is available
   * @param configId Optional configuration ID
   * @returns Whether it is available
   */
  async isAvailable(configId?: string): Promise<boolean> {
    try {
      const apiConfig = await this.getApiConfig(configId);
      return !!apiConfig?.config?.apiKey;
    } catch {
      return false;
    }
  }

  /**
   * Get the list of available models
   * @returns List of model info
   */
  async getAvailableModels(): Promise<
    Array<{ provider: string; model: string }>
  > {
    try {
      const userSettings = await this.storageService.getUserSettings();
      return userSettings.apiConfigs.map((config) => ({
        provider: getProtocolFamilyLabel(config.protocolFamily),
        model: config.config.model,
      }));
    } catch {
      return [];
    }
  }

  /**
   * Get the API configuration
   */
  private async getApiConfig(
    configId?: string,
    forceProvider?: ApiProtocolFamily,
  ): Promise<ApiConfigItem | null> {
    const userSettings = await this.storageService.getUserSettings();

    if (configId) {
      return (
        userSettings.apiConfigs.find((config) => config.id === configId) || null
      );
    }

    if (forceProvider) {
      return (
        userSettings.apiConfigs.find(
          (config) => config.protocolFamily === forceProvider,
        ) || null
      );
    }

    // Use the currently active configuration
    return (
      userSettings.apiConfigs.find(
        (config) => config.id === userSettings.activeApiConfigId,
      ) || null
    );
  }

  /**
   * Build the request body
   */
  private buildRequestBody(
    prompt: string,
    config: ApiConfig,
    options: UniversalApiOptions,
  ): any {
    const messages = [];

    // Add the system prompt
    if (options.systemPrompt) {
      messages.push({ role: 'system', content: options.systemPrompt });
    }

    // Add the user prompt
    messages.push({ role: 'user', content: prompt });

    let requestBody: any = {
      model: config.model,
      messages: messages,
      temperature: options.temperature ?? config.temperature ?? 0.7,
    };

    if (options.maxTokens) {
      requestBody.max_tokens = options.maxTokens;
    }

    // Merge custom parameters
    if (options.customParams) {
      requestBody = mergeCustomParams(requestBody, options.customParams);
    } else if (config.customParams) {
      requestBody = mergeCustomParams(requestBody, config.customParams);
    }

    return requestBody;
  }

  /**
   * Send the API request
   */
  private async sendRequest(
    requestBody: any,
    config: ApiConfig,
    timeout?: number,
  ): Promise<Response> {
    return await sendApiRequest(requestBody, config, getApiTimeout(timeout));
  }

  /**
   * Parse the API response
   */
  private parseResponse(
    data: any,
    prompt: string,
    apiConfig: ApiConfigItem,
    rawResponse?: boolean,
  ): UniversalApiResult {
    try {
      let content = '';
      let usage: any = undefined;

      if (isGeminiFamily(apiConfig.protocolFamily)) {
        content = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
        if (data.usageMetadata) {
          usage = {
            promptTokens: data.usageMetadata.promptTokenCount,
            completionTokens: data.usageMetadata.candidatesTokenCount,
            totalTokens: data.usageMetadata.totalTokenCount,
          };
        }
      } else {
        // OpenAI-compatible format (OpenAI, DeepSeek, SiliconFlow, etc.)
        content = data.choices?.[0]?.message?.content || '';
        if (data.usage) {
          usage = {
            promptTokens: data.usage.prompt_tokens,
            completionTokens: data.usage.completion_tokens,
            totalTokens: data.usage.total_tokens,
          };
        }
      }

      const result: UniversalApiResult = {
        success: true,
        prompt,
        content,
        model: apiConfig.config.model,
        provider: getProtocolFamilyLabel(apiConfig.protocolFamily),
      };

      // Add token usage info
      if (usage) {
        result.usage = usage;
      }

      // If the raw response is requested
      if (rawResponse) {
        result.rawData = data;
      }

      return result;
    } catch (_) {
      return {
        success: false,
        prompt,
        content: '',
        error: 'Failed to parse API response',
      };
    }
  }
}

// Export convenience instance and methods
export const universalApi = UniversalApiService.getInstance();

/**
 * Universal AI call function (global convenience method)
 * @param prompt Prompt
 * @param options Optional configuration
 * @returns API response result
 */
export async function callAI(
  prompt: string,
  options?: UniversalApiOptions,
): Promise<UniversalApiResult> {
  return universalApi.call(prompt, options);
}

/**
 * Quick AI call function
 * @param prompt Prompt
 * @param systemPrompt System prompt (optional)
 * @returns API response result
 */
export async function quickAI(
  prompt: string,
  systemPrompt?: string,
): Promise<UniversalApiResult> {
  return universalApi.quickCall(prompt, systemPrompt);
}
